binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args: []
excluded-modules:
- Day1/Specs.hs
- Day2/Specs.hs
- Day3/Specs.hs
- Day4/Specs.hs
- Day5/Specs.hs
