module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: default
cabal-file: project.cabal
version: 1
ghc-args: []
excluded-modules:
- Setup.hs
- src/Day07/Wires.hs
- test/Day07/WiresSpec.hs
- test/Spec.hs
